FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src

COPY "BuildingBlocks/EventBus/EventBus.csproj" "BuildingBlocks/EventBus/EventBus.csproj"
COPY "BuildingBlocks/EventBusRabbitMQ/EventBusRabbitMQ.csproj" "BuildingBlocks/EventBusRabbitMQ/EventBusRabbitMQ.csproj"
COPY "BuildingBlocks/IntegrationEventLogEF/IntegrationEventLogEF.csproj" "BuildingBlocks/IntegrationEventLogEF/IntegrationEventLogEF.csproj"
COPY "Services/DREDD/DREDD.API/DREDD.API.csproj" "Services/DREDD/DREDD.API/DREDD.API.csproj"

RUN dotnet restore Services/DREDD/DREDD.API/DREDD.API.csproj -nowarn:msb3202,nu1503
COPY . .
WORKDIR /src/Services/DREDD/DREDD.API
RUN dotnet build --no-restore -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]